## Importing libraries

In [1]:
import numpy as np
import pandas as pd

## loading the dataset

In [2]:
df = pd.read_csv("../5 lab5 simple linear regression/Salary_Data.csv")
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [3]:
x, y

(array([[ 1.1],
        [ 1.3],
        [ 1.5],
        [ 2. ],
        [ 2.2],
        [ 2.9],
        [ 3. ],
        [ 3.2],
        [ 3.2],
        [ 3.7],
        [ 3.9],
        [ 4. ],
        [ 4. ],
        [ 4.1],
        [ 4.5],
        [ 4.9],
        [ 5.1],
        [ 5.3],
        [ 5.9],
        [ 6. ],
        [ 6.8],
        [ 7.1],
        [ 7.9],
        [ 8.2],
        [ 8.7],
        [ 9. ],
        [ 9.5],
        [ 9.6],
        [10.3],
        [10.5]]),
 array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
         54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
         61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
         98273., 101302., 113812., 109431., 105582., 116969., 112635.,
        122391., 121872.]))

## Splitting the dataset into train and test set

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=1/3)

## Training the simple linear regression model on the training set

In [7]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

## Predicting the test set results

In [8]:
lr.predict([[3.7]])

array([60807.8349883])

In [9]:
y_pred = lr.predict(x_test)

In [10]:
y_pred

array([ 56183.71269366,  56183.71269366, 121846.24927759,  64507.13282402,
       114447.65360616,  63582.30836509,  82078.79754366,  45085.81918652,
        92251.86659188,  60807.8349883 ])

## y = m * x + c

In [12]:
m = lr.coef_

In [13]:
c = lr.intercept_

In [14]:
y = m * 3.7 + c

In [15]:
y

array([60807.8349883])

## Performance Measures

In [17]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [18]:
print("MAE", mean_absolute_error(y_test, y_pred))

MAE 5017.952834462911


In [19]:
print("MSE", mean_squared_error(y_test, y_pred))

MSE 36944238.486296296


In [20]:
print("RMSE", np.sqrt(mean_squared_error(y_test, y_pred)))

RMSE 6078.17723386677


In [23]:
print("r2 score", r2_score(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

r2 score 0.9498923531913538


In [24]:
# Adjusted R2 Score
1 - ((1 - r2) * (30 - 1) / (30 - 1 - 1))

0.9481027943767593